### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joelmccracken** [sanchom/sanchom.github.io#24]
I'm looking at options for implementing footnotes, and I think I'd like to use what you have. I don't see a license anywhere, though. Am I free to use it?

**Comment by sanchom** [comment]
Thanks for asking! Yes, please use it. I just added a [license](https://github.com/sanchom/sanchom.github.io/blob/master-source/LICENSE.txt) that should let you re-use any of the footnote implementation. Let me know if that isn't enough.

**Comment by joelmccracken** [comment]
Looks good to me, thank you!

The "source is open, prose is not" Its an interesting issue. I feel like there should be a better way to specify that.
